### ISSUE TITLE
Include guidelines for using Aura

### ISSUE THREAD

**Issue by ncbaratta** [redhat-documentation/community-collaboration-guide#110]
Once Aura is public, we need to include guidelines for using it

**Comment by ncbaratta** [comment]
Include the directory structure recommended by Aura

**Comment by ncbaratta** [comment]
Once Aura is open sourced we should update chapter 6 with info from those guidelines.

**Comment by pmkovar** [comment]
@ncbaratta I don't think Aura is still a thing, let's close this?
