### ISSUE TITLE
Add license for community-collaboration-guide

### ISSUE THREAD

**Issue by pmkovar** [redhat-documentation/community-collaboration-guide#119]
The Modular Documentation Reference Guide is licensed under CC-BY-SA-4.0, so let's follow suit and add a CC license to the community-collaboration-guide. 

See https://github.com/redhat-documentation/modular-docs/issues/78.

**Comment by pmkovar** [comment]
@ncbaratta I forgot to mention this in the last meeting, can we add it to the agenda for the next meeting?

**Comment by ncbaratta** [comment]
Done! :)

**Comment by ncbaratta** [comment]
Resolved per a vote on 2 April 2019 : https://github.com/redhat-documentation/community-collaboration-guide/commit/4cdec7286c52c3ec2770c377e2cbfde6530adb16
