### ISSUE TITLE
Add an example of general publication methods

### ISSUE THREAD

**Issue by adahms** [redhat-documentation/community-collaboration-guide#21]
A description of how to publish content using some general methods used by existing communities must be added to the '==== Other' section of the 'structure.adoc' file. This includes a brief introduction to each method and how it works, and a link to a location where readers can find more information.

**Comment by adahms** [comment]
Assigning to Mikey for review.

Mikey - this is the section we discussed during the last project meeting about adding some examples of existing communities. Feel free to change the 'Other' section into a set of sections, with one for each example.

**Comment by nengard** [comment]
@thatdocslady Just checking in here, do you have anything to add?

**Comment by thatdocslady** [comment]
@nengard yes! Sorry it's been crazy and I haven't had a chance to compile my thoughts on this yet. If someone else is itching for this please pass it on, otherwise I should have more bandwidth in the coming weeks :)

**Comment by nengard** [comment]
Okay @thatdocslady this content is now living in the publishing.adoc file.

**Comment by nengard** [comment]
I'm not sure if we really need an 'other' section. I have commented this out, we can revisit if we think we need it at a later date. https://github.com/redhat-documentation/community-collaboration-guide/pull/59
