### ISSUE TITLE
Add an example of how to publish content using the microservices method

### ISSUE THREAD

**Issue by adahms** [redhat-documentation/community-collaboration-guide#24]
A description of how to publish content using the microservices method must be added to the '==== Microservices' section of the 'structure.adoc' file. This includes a brief introduction to the method and how it works, and a link to a location where readers can find more information.

**Comment by nengard** [comment]
This content is now living in the publishing.adoc file.

**Comment by nengard** [comment]
Work on this will begin after November 17th.

**Comment by nengard** [comment]
I have commented this section out on the publishing.adoc file for now.

**Comment by ncbaratta** [comment]
Invalid issues
