### ISSUE TITLE
Add general examples to illustrate community readiness

### ISSUE THREAD

**Issue by adahms** [redhat-documentation/community-collaboration-guide#25]
Some generalized examples that illustrate community readiness to move to an upstream-downstream collaboration workflow must be added to the '=== Evaluating the Framework' section of the 'introduction.adoc' file.

**Comment by nengard** [comment]
@shaunix this might also be an area we can use your help.  If you want I can assign this to you :)

**Comment by shaunix** [comment]
You can assign to me. I'll look at it next week.

**Comment by nengard** [comment]
After our meeting today, we feel this is probably not necessary at this time.  If folks have questions on how https://redhat-documentation.github.io/community-collaboration-guide/#ccg-community-evaluation has worked for other communities we can add examples of this filled out with values for communities we have worked with in the past.
