### ISSUE TITLE
Improve the guide structure

### ISSUE THREAD

**Issue by pmkovar** [redhat-documentation/community-collaboration-guide#50]
There were a few structural issues that I addressed with #49, but a few more are remaining. The ToC should follow a standard workflow used by a typical upstream documentation project.

* Decide on the structure (+ create repos if needed)
* Migrate content if applicable
* Update
* Render locally and/or build
* Publish
* Sync with downstream

Let's change the guide structure to reflect that. @nengard Thoughts?

**Comment by pmkovar** [comment]
> But, you are missing a few other steps. There is the step of deciding if you can even work with the community at all. And then there are the tips for working with a community and communication guidelines and such. 

Good point. This wasn't supposed to be a definite list or a complete ToC. Deciding if you can even work with the community should probably precede all the other steps. Tips etc. could live in an appendix, if we want to (visually) separate it from the workflow steps?

**Comment by nengard** [comment]
Sounds great to me!  So maybe:

- Introduction
- Evaluating Community
- Communicating with Community
- Decide on the structure (+ create repos if needed)
- Migrate content if applicable
- Update
- Render locally and/or build
- Publish
- Sync with downstream
- Tips & Tricks for working with communities

**Comment by pmkovar** [comment]
LGTM, thanks.

**Comment by nengard** [comment]
Replace Communicating with Collaborating - and move this above evaluating.

**Comment by nengard** [comment]
This is done for the chapters we have content in - comments added as placeholders for chapters we don't have yet.
