### ISSUE TITLE
Add Tips & Tricks

### ISSUE THREAD

**Issue by nengard** [redhat-documentation/community-collaboration-guide#66]
We have a section for Tips & Tricks: https://redhat-documentation.github.io/community-collaboration-guide/#ccg-tips-tricks , I think we should comment this out until we actually have something to add.  Does anyone have anything they'd like to add to this section? Or should we comment it out?

@bhardesty , @pmkovar , or @shaunix you might have some tips you'd like to share.

**Comment by pmkovar** [comment]
It might make more sense to try to include Tips & Tricks in individual chapters.

**Comment by nengard** [comment]
Yeah, that would be nice!

**Comment by nengard** [comment]
Closing this in favor of separate issues for each chapter.
