### ISSUE TITLE
Add mailing list to contacts

### ISSUE THREAD

**Issue by ncbaratta** [redhat-documentation/community-collaboration-guide#67]
We have a section for contacts: https://redhat-documentation.github.io/community-collaboration-guide/#ccg-contacts 

Should we have this just downstream? Do any of us want to put our email addresses out there?

**Comment by JStickler** [comment]
When I brought this up in discussions, I was thinking that open source projects tend to have some way to contact them with questions (IRC, mailing list).  What mechanism do we want to use to let people contact the team with questions?

**Comment by nengard** [comment]
I have requested a public mailing list.

**Comment by nengard** [comment]
I've moved this section to earlier in the guide and am still awaiting information from IT in making the list public.
