### ISSUE TITLE
Add instructions for embedding help in guides

### ISSUE THREAD

**Issue by ncbaratta** [redhat-documentation/community-collaboration-guide#69]
It might be nice to have a section on how we can embed UI help in our AsciiDoc in the publishing chapter.

**Comment by nengard** [comment]
@jenmalloy do you think you could write up something short for this section?

**Comment by jenmalloy** [comment]
@nengard, yes, this fell off my radar. Added it to my to-do list

**Comment by ncbaratta** [comment]
Out of scope
