### ISSUE TITLE
Synchronizing Content

### ISSUE THREAD

**Issue by adahms** [redhat-documentation/community-collaboration-guide#7]
Write a detailed overview of how to synchronize content between an upstream and downstream source in the '=== Synchronizing Content' section of the structure.adoc file.

This overview must describe the following topics:

- Why content must be synchronized
- The mechanism used to synchronize content

The content should provide an overview of synchronization that discusses the need for content to be synchronized with the downstream without exposing any internal, downstream links. For example, mention that Red Hat documentation stores content in a Git repository, and that content must be synchronized there so that it can be published.

**Comment by adahms** [comment]
Assigning to Fintan for review.

Fintan - this is the issue we discussed during the last project meeting to provide content on synchronizing content.

We discussed that we would start by documenting the batch commit method you have been working on, so it looks like we will need a general introduction to synchronizing content, and a specific section on how to do so using the batch commit method.

Let me know if you have any questions!

**Comment by nengard** [comment]
@fbolton will you have a chance to work on this in the coming weeks?

**Comment by fbolton** [comment]
@nengard, so the "batch commit" approach to synchronizing content is already written up and merged. I haven't thought about this issue much since adding that content. I guess the next question is: what other synchronization methods do we want to document/support?

**Comment by nengard** [comment]
Oh, I guess I didn't think about that.  I'll add it as a question for our next meeting.
