### ISSUE TITLE
Add repo directory template

### ISSUE THREAD

**Issue by nengard** [redhat-documentation/community-collaboration-guide#70]
It would be nice to have repo structure folders that folks could clone to their repository. It would match the structures we define in the guide: https://redhat-documentation.github.io/community-collaboration-guide/#ccg-project-structure

**Comment by pmkovar** [comment]
I believe this should live in a separate repo.

Also, let's consider using https://cookiecutter.readthedocs.io/en/latest/ as a template system for this.

**Comment by nengard** [comment]
I'd say a separate repo here in our group and yes we should totally share!

**Comment by nengard** [comment]
3.1-3.3 @JStickler already wrote.
