### ISSUE TITLE
Fill content gaps for site builders

### ISSUE THREAD

**Issue by pmkovar** [redhat-documentation/community-collaboration-guide#74]
So far, we cover asciibinder, github pages, and there is an item open for microservices (#24). As there are many other site builders for AsciiDoc (and other formats) that are employed within Red Hat projects, such as jekyll or middleman, we should cover those too.

Coverage should be based on analysis of what we actually use in projects.

**Comment by nengard** [comment]
Okey dokey, are these tools you are using? Can you write these sections?

**Comment by pmkovar** [comment]
I don't think I can write all the sections, let's take a look at the community survey results and reach out to involved parties to see if they can share knowledge with us wrt tool deployment. ;)

**Comment by ncbaratta** [comment]
Closing - will open new tickets for specific site builders
