### ISSUE TITLE
Modular structure

### ISSUE THREAD

**Issue by pmkovar** [redhat-documentation/community-collaboration-guide#75]
Using this as a tracker for turning the current structure into a modular document.

**Comment by pmkovar** [comment]
# Overview

Currently, the document's structure is pretty linear in that each chapter follows a logical step for planning, creating and managing a documentation project. This requires the reader, for example, to jump from rendering content to building to publishing to syncing because the chapters cover a number of tools, however, a typical use case is that the reader is only interested in using one tool.

# Potential assemblies

Based on the concepts from https://redhat-documentation.github.io/modular-docs/, we could create module assemblies that would focus on the following areas:

* [Documentation project] maintenance phase (planning, setup, development, building, publishing, syncing, etc.)
* A specific toolchain (or format)
* Other?

**Comment by pmkovar** [comment]
Tagging @nengard

**Comment by nengard** [comment]
Looks good, I'd say this is a phase 2 kind of thing.  We want to get the guide content complete and then we can talk about reorg and creating other assemblies.  Putting this on agenda for tomorrow.

**Comment by nengard** [comment]
Per our meeting today: Team agrees this is a good idea once the guide is content complete.

**Comment by ncbaratta** [comment]
We're going to hold off on this until after the mod docs training the last of which is in the US at the end of June.

**Comment by adahms** [comment]
Looks like this one has been open for a while, but now could be a good time to address it.

@ncbaratta - any issues with me creating a PR for this one for your team to review?

**Comment by ncbaratta** [comment]
Not at all!! Do it!! :)

**Comment by adahms** [comment]
As a quick update, I *am* working this - it's just taking a little time as I break the task out over a number of days. It's all moving ahead, I promise. :)

**Comment by adahms** [comment]
@pmkovar @ncbaratta - you might have seen this already, but I have now raised a WIP PR for this issue in #123.

There is still some work to go, but the majority of structural changes are done - only in community/master.adoc for now - and content split into assemblies and modules. 

Raising a WIP so you can check and see what you think of the work done already in case we need to alter course and so that you have visibility into progress.

**Comment by adahms** [comment]
The corresponding PR has now been merged.

Closing.
